### PR TITLE
[KOGITO-4553] Panic when even number of proto files are available in …

### PR DESCRIPTION
**Pull request by sutaakar**
…appplication

https://issues.redhat.com/browse/KOGITO-4553

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — COMMENTED** [review]
The problem was debug logging??

**Comment by sutaakar** [comment]
yes, the logger accepts vararg as a parameter and enforces even number of parameters. When array was provided as a parameter the Go will join it with the `"Protobuf List"` string and pass all as vararg.

**Review by ricardozanini — APPROVED** [review]
Thanks!

**Comment by vaibhavjainwiz** [comment]
Its hard to find changes with new code coverage tool

**Review by vaibhavjainwiz — APPROVED** [review]
LGTM

**Comment by sutaakar** [comment]
Is the code coverage tool actually useful for you? I find it rather confusing.

**Comment by vaibhavjainwiz** [comment]
I think it will be helpful if it could generate seperate report for code coverage rather them mix it in file changes of PR.

**Comment by ricardozanini** [comment]
> I think it will be helpful if it could generate seperate report for code coverage rather them mix it in file changes of PR.

I also find it super confusing. I don't remember adding this option to our CI. @vaibhavjainwiz I think you made the last changes? Can you revert back?

**Pull request merged**
