### PR TITLE
[KOGITO-686] - Migrating CI to GitHub Actions

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.redhat.com/browse/KOGITO-686

I'm opening this one, but I'm not willing to merge since [GH Actions](https://github.com/ricardozanini/kogito-cloud-operator/pull/6/checks?check_run_id=387876203) takes a considerable amount of time to finish than [CircleCI](https://app.circleci.com/jobs/github/kiegroup/kogito-cloud-operator/596).

The `go mod tidy` step takes up to 6 minutes to finish, while CircleCI takes up to 2. I tried to add a cache solution, but it only caches up to 2GB. If exceeds, there's no cache at all. :cry: 

Well, I'm opening this for discussion: @spolti @radtriste @sutaakar @msmagnanijr @mwringe what do you guys think?

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
(ignore the check failure, I removed the `.circleci` directory)

**Comment by sutaakar** [comment]
@ricardozanini Do you know what causes this slowness? Is it caused by slower machines on GitHub or is it related to environment?

**Comment by ricardozanini** [comment]
Seems a slowness in the network, it takes a lot of time to download all the dependencies. Could be improved when migrating to Go 1.13

**Comment by sutaakar** [comment]
I am ok with postponing it to Go 1.13

**Comment by radtriste** [comment]
I do agree with Karel. If Go 1.13 will improve it, we should wait for it in this repository.

**Comment by ricardozanini** [comment]
Let's add [KOGITO-857](https://issues.redhat.com/browse/KOGITO-857) (Upgrade Operator SDK to 0.13.0 and Go to 1.13) as a blocker to this and mark it "on hold" then.

**Comment by spolti** [comment]
+1 for wait to golang version 1.13;

**Comment by ricardozanini** [comment]
Closing as "Won't Do". See: https://issues.redhat.com/browse/KOGITO-686?focusedCommentId=13952522&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13952522

**Pull request closed without merging**
