### PR TITLE
[KOGITO-691] - Creating new tags when ImageStream already exists

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.redhat.com/browse/KOGITO-691

In this PR we add the possibility to have multiple image tags for the same image stream.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
@ricardozanini What will/should happen in case image stream is already available in openshift namespace, however requited image stream tag is not there?

**Comment by ricardozanini** [comment]
Will be created a new tag in the current namespace. Our user doesn’t have permissions on OpenShift namespace

**Comment by radtriste** [comment]
Tested:
No imagestream present => OK (imagestream and tag created)
Imagestream present in NS but not the tag => OK (imagestreamtag created)
Imagestream and tag are already there => OK (nothing happen)
Imagestream present in openshift NS but not in NS => OK (imagestream and tag created)

**Comment by ricardozanini** [comment]
Waiting OLM PR to get merged.

**Pull request merged**
