### PR TITLE
[KOGITO-3335] Tests: Split current tests to operator and integration

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
Have you disabled #558?

**Comment by sutaakar** [comment]
@ricardozanini no, I have just found out that this PR exists

**Comment by ricardozanini** [comment]
@sutaakar can you rebase please?

**Comment by sutaakar** [comment]
Done
/jenkins test

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
