### PR TITLE
[KOGITO-3586] BDD tests should have unique namespace

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-3586

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
@radtriste It may be simpler to use map, that way you can avoid looping through the slice to check whether the namespace exists. Also, the race condition could happen there.
What about using `sync.Map` as is done in logging?

**Comment by radtriste** [comment]
@sutaakar updated

**Review by sutaakar — APPROVED** [review]
Looks good to me, thanks

**Pull request merged**
