### PR TITLE
[KOGITO-3300] - Improving tests and ignoring project not in the context

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-3300

The CLI was checking every time for the namespace in the current context in the kubeconfig file. When a brand new kubeconfig file was created, without a namespace in the current context, the cli would fail to perform any command unless `kogito use-ns NAMESPACE` was used before.

There are two new test cases to validate this scenario.

Aside, I removed the `I` from the interfaces.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]
Looks good to me.

**Comment by ricardozanini** [comment]
@Kaitou786 were you able to test this PR in the BDD tests?

**Comment by Kaitou786** [comment]
> @Kaitou786 were you able to test this PR in the BDD tests?

Yes, I added this commit in #545 seems to work as expected :)

**Review by Kaitou786 — APPROVED** [review]

**Comment by ricardozanini** [comment]
@spolti once you approve this one, we can include this fix in the 0.15 release.

**Pull request merged**
