### PR TITLE
Revert "KOGITO-3514 BDD: switch to docker container engine (#594)"

### PR DESCRIPTION
**Pull request by Sgitario**
This reverts commit 2c04122dcb35946ff413798148a7081db30e8c6c. Check whether is working fine now ...

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
@radtriste this PR check worked fine, does it mean that we can revert KOGITO-3514 (using podman as container engine back)? or do you know how to reproduce the original issue?

**Comment by radtriste** [comment]
That is the tricky part :D
Operator PR checks are done on AWS Jenkins whereas nightly/release pipelines are done on RHBA Jenkins.
And it used to fail on RHBA Jenkins ...
Need to test the `kogito-operator-deploy` pipeline with podman

**Comment by Kaitou786** [comment]
I checked on the RHBA node, it still fails using podman (in this [pipeline](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kaitou786/job/maven-build/)).

**Comment by Sgitario** [comment]
> I checked on the RHBA node, it still fails using podman (in this [pipeline](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kaitou786/job/maven-build/)).
> EDIT: The problem is most likely from old podman package available on the node. As the same test passes on a [RHEL8 based node](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kaitou786/job/rhel-8-image-test/)

Ok, will close this PR and leave the ticket opened.

**Pull request closed without merging**
