### PR TITLE
[1.2.x] Set next snapshot

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
gonna launch the smoke tests once https://github.com/kiegroup/kogito-images/pull/333 is merged and 1.2 nightly images deployed

**Comment by Kaitou786** [comment]
Shouldn't this be merged aganst 1.2.x branch instead of master?

**Comment by radtriste** [comment]
nice catch. changed. thx @Kaitou786

**Review by Kaitou786 — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Pull request merged**
