### PR TITLE
[KOGITO-3866] - Operator print error logs when KogitoRuntime delete

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Many thanks for submitting your Pull Request :heart:! 

Jira issue : https://issues.redhat.com/browse/KOGITO-3866

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Great job!

**Review by Kaitou786 — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by ricardozanini** [comment]
@sutaakar do you want to verify before merging?

**Comment by sutaakar** [comment]
Sure, I will check

**Review by sutaakar — APPROVED** [review]
Looks good to me, works as expected.

**Comment by ricardozanini** [comment]
@vaibhavjainwiz could you please take a look in the CI errors? It seems a problem in the CRD version maybe? cc @sutaakar

**Comment by sutaakar** [comment]
`The CustomResourceDefinition "kogitobuilds.app.kiegroup.org" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions`
The old CRD needs to be manually deleted.

**Comment by ricardozanini** [comment]
@radtriste do you think we still have time for a cherry pick? Would be nice to have this one on 1.0.0

**Comment by radtriste** [comment]
@ricardozanini I think that this one can wait for the next release. We already had many problems on the pipeline and I would not want to add things which are not "pipeline fix". I don't think it is extremely urgent to have this or ?

**Comment by ricardozanini** [comment]
Agreed, we are about to release another version nevertheless.

**Comment by Kaitou786** [comment]
@radtriste  @ricardozanini I think we should atleast add this in `known bugs` section in our release notes of 1.0, wdyt?

**Comment by ricardozanini** [comment]
Yes, I think it's doable. Can you send a PR to the release notes on 1.x? The other bug @vaibhavjainwiz fixed also needs to be there.

**Comment by Kaitou786** [comment]
@ricardozanini the [PR](https://github.com/kiegroup/kogito-cloud-operator/pull/665)

**Pull request merged**
