### PR TITLE
[KOGITO-1453] Refactor shell scripts file discovery logic

### PR DESCRIPTION
**Pull request by LCaparelli**
https://issues.redhat.com/browse/KOGITO-1453

Simplify file globbing logic and adjust exit status to improve user
feedback.

Also add feedback for when no deployment files are found. This scenario
yields exit code 3, avoiding UNIX reserved exit codes.

Signed-off-by: Lucas Caparelli <lucas.caparelli112@gmail.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by spolti** [comment]
Great, sounds good tome, the only missing thing is the jira :)

**Comment by ricardozanini** [comment]
> Great, sounds good tome, the only missing thing is the jira :)

I told him that opening a JIRA won't be required, @LCaparelli do you mind [opening a JIRA](https://issues.redhat.com/projects/KOGITO/)? You can assign it to me and I'll fill in the blanks. Thanks!

**Comment by LCaparelli** [comment]
> I told him that opening a JIRA won't be required, @LCaparelli do you mind opening a JIRA? You can assign it to me and I'll fill in the blanks. Thanks!

Sure thing, here it is: [KOGITO-1453](https://issues.redhat.com/projects/KOGITO/issues/KOGITO-1453). :-)

I tried filling some of it the best I could, sorry if something isn't quite right.

**Comment by ricardozanini** [comment]
Adjusted. @LCaparelli do you mind also reviewing those? I believe they might have some room for improvements using this same technique.

https://github.com/kiegroup/kogito-cloud-operator/blob/master/hack/run-tests.sh#L91
https://github.com/kiegroup/kogito-cloud-operator/blob/master/hack/scorecard.sh#L17

Thanks!

**Comment by LCaparelli** [comment]
> Adjusted. @LCaparelli do you mind also reviewing those? I believe they might have some room for improvements using this same technique.
> 
> https://github.com/kiegroup/kogito-cloud-operator/blob/master/hack/run-tests.sh#L91
> https://github.com/kiegroup/kogito-cloud-operator/blob/master/hack/scorecard.sh#L17
> 
> Thanks!

@ricardozanini pushed a change in scorecard.sh along with some nitpicking on 3.11deploy.sh regex so it matches scorecard.sh.

I didn't modify run-tests.sh similarly as the file array in there will be used to download the file from github using curl. Since the files are not currently in the filesystem it's not possible apply the same technique.

Thanks!

**Pull request merged**
