### PR TITLE
[KOGITO-3678] Add test coverage for Knative functionality

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-3678

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
Marked as WIP as I need to figure out automation for Knative installation.
Right now the test pass when Knative is already installed in advance.

**Comment by sutaakar** [comment]
Marking as ready, Knative installation will be quite complex and will deserve separate PR.
Right now the test works when Knative eventing is preinstalled.

**Comment by sutaakar** [comment]
Test failures are caused by cancelled builds, no idea why they got cancelled.

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
> Marking as ready, Knative installation will be quite complex and will deserve separate PR.
> Right now the test works when Knative eventing is preinstalled.

If we merge the PR, and knative not installed on test Openshift, we may have the test always failing...
shouldn't we `@disabled` it until we have a proper solution ? or we have to make sure knative is installed on the cluster ...

**Comment by sutaakar** [comment]
@radtriste Disabled for now.

**Review by radtriste — APPROVED** [review]

**Pull request merged**
