### PR TITLE
[KOGITO-3968] - Add support to deploy Kogito services from SW files

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-3968

To deploy the [SW greetings example](https://github.com/kiegroup/kogito-examples/tree/master/serverless-workflow-greeting-quarkus) from the source, do:

```bash
$ kogito deploy sw-greetings cmd/kogito/command/deploy/testdata/greetings.sw.json --image-runtime quay.io/kiegroup/kogito-quarkus-jvm-ubi8:1.0 --image-s2i quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0

Kogito Build Service successfully installed in the Project kogito-3968.
Check the Service status by running 'oc describe kogitobuild/sw-greetings -n kogito-3968'
File(s) found: cmd/kogito/command/deploy/testdata/greetings.sw.json.
Triggering the new build
The requested file(s) was successfully uploaded to OpenShift, the build sw-greetings-builder-1 with this file(s) should now be running. To see the logs, run 'oc logs -f bc/sw-greetings-builder -n kogito-3968'
Kogito Service successfully installed in the Project kogito-3968.
Check the Service status by running 'oc describe kogitoruntime/sw-greetings -n kogito-3968'
To more easily manage your Kogito Service install Data Index Service and Process Instance Management. 
For how to install see: https://docs.jboss.org/kogito/release/latest/html_single/#con-kogito-operator-with-data-index-service_kogito-deploying-on-openshift
and https://docs.jboss.org/kogito/release/latest/html_single/#con-management-console_kogito-developing-process-services
```

Soon you should see:

```bash
$ oc get builds

NAME                     TYPE     FROM     STATUS    STARTED         DURATION
sw-greetings-builder-1   Source   Binary   Running   3 minutes ago   
```

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by ricardozanini** [comment]
Working locally:

```bash
$ oc logs -f sw-greetings-6f6754dfd9-xjvwp
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-12-07 20:29:31,324 INFO  [io.quarkus] (main) project 1.0-SNAPSHOT on JVM (powered by Quarkus 1.10.0.Final) started in 2.717s. Listening on: http://0.0.0.0:8080
2020-12-07 20:29:31,326 INFO  [io.quarkus] (main) Profile prod activated. 
2020-12-07 20:29:31,326 INFO  [io.quarkus] (main) Installed features: [cdi, kogito, resteasy, resteasy-jackson, servlet, smallrye-openapi, swagger-ui]





Hello from JSON Workflow, John
Saludos desde JSON Workflow, John
```

/jenkins test

**Review by sutaakar — APPROVED** [review]
Looks good to me, works as expected.

**Review by spolti — APPROVED** [review]

**Review by vaibhavjainwiz — APPROVED** [review]
LGTM

**Review by Kaitou786 — APPROVED** [review]

**Comment by ricardozanini** [comment]
Well I guess we will have to wait until tomorrow to test this.

**Pull request merged**
