### PR TITLE
[KOGITO-2871] - Remove deprecated properties from kogito-cloud-operator

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Jira issue : https://issues.redhat.com/browse/KOGITO-2871

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by vaibhavjainwiz** [comment]
Jenkins, test this.

**Comment by Kaitou786** [comment]
Jenkins test this

**Comment by sutaakar** [comment]
Jenkins, test this

**Comment by ricardozanini** [comment]
Please check the lint failure.

**Comment by radtriste** [comment]
Jenkins test this

**Pull request merged**
