### PR TITLE
[KOGITO-2396] - Integrate `golangci-lint` in `hack/go-lint.sh`

### PR DESCRIPTION
**Pull request by Kaitou786**
See: https://issues.redhat.com/browse/KOGITO-2396
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
@Kaitou786 the doc part should be coordinated with: https://github.com/kiegroup/kogito-cloud-operator/pull/375

You may send another PR after this one to fix the docs after we merge #375, since this one is somewhat urgent.

**Comment by Kaitou786** [comment]
@ricardozanini ah, yes that can be done. I am thinking instead of hardcoding the version to v1.27.0 How about leaving it blank so it downloads the latest version of golangci-lint?

**Comment by ricardozanini** [comment]
> @ricardozanini ah, yes that can be done. I am thinking instead of hardcoding the version to v1.27.0 How about leaving it blank so it downloads the latest available version of golangci-lint?

hmm in my tests the latest downloaded version was the last commit, not the last tag. But if it's not true, go ahead!

**Comment by Kaitou786** [comment]
> > @ricardozanini ah, yes that can be done. I am thinking instead of hardcoding the version to v1.27.0 How about leaving it blank so it downloads the latest available version of golangci-lint?
> 
> hmm in my tests the latest downloaded version was the last commit, not the last tag. But if it's not true, go ahead!
> 
> EDIT: if that works, do you mind sending a PR to the Nexus Operator as well? smile

Ah yes,just tested it downloads the latest commit and not the latest tag. Updated PR with `v1.27.0`

**Comment by Kaitou786** [comment]
Updated PR to keep both `golint` and `golangci-lint` as even after enabling `goling` in `golangci-lint` it doesn't give warnings/errors for comment related issue.

**Pull request merged**
