### PR TITLE
Update comments.yml for jenkins tests

### PR DESCRIPTION
**Pull request by r00ta**
The bot commented with `Jenkins, test this.` but on my pr the build did not start. The correct syntax is `Jenkins test this` isnt't? 

Sorry for the missing jira ticket, feel free to close it if I'm wrong

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Kaitou786** [comment]
@r00ta , the problem is not in the comment. `Jenkins, test this.` is also part of reg exp for triggering the CI. The main problem we are facing is accepting those comments from a bot, currently, we've set it up so it accepts comments from any member in kiegroup. I'm testing out the ways I can give this bot access for commenting, the problem is it doesn't have any GH accounts :(

**Comment by ricardozanini** [comment]
> Hey, @r00ta , the problem is not in the comment. `Jenkins, test this.` is also part of reg exp for triggering the CI. The main problem we are facing is accepting those comments from a bot, currently, we've set it up so it accepts comments from any member in kiegroup. I'm testing out the ways I can give this bot access for commenting, the problem is it doesn't have any GH accounts :(

I don't get it. Why we need commas and periods? Won't make sense changing it in the CI? I understand that's not the bot's problem, but we could change there and reflect that change in here. I would go further and change it to `/jenkins test` only. This way when we add the commands for the bot like `/assign`, commands would be standardized.

**Comment by Kaitou786** [comment]
> > Hey, @r00ta , the problem is not in the comment. `Jenkins, test this.` is also part of reg exp for triggering the CI. The main problem we are facing is accepting those comments from a bot, currently, we've set it up so it accepts comments from any member in kiegroup. I'm testing out the ways I can give this bot access for commenting, the problem is it doesn't have any GH accounts :(
> 
> I don't get it. Why we need commas and periods? Won't make sense changing it in the CI? I understand that's not the bot's problem, but we could change there and reflect that change in here. I would go further and change it to `/jenkins test` only. This way when we add the commands for the bot like `/assign`, commands would be standardized.
> 
> EDIT: loved the new avatar. <3

Ah okay. the current change that @r00ta  did will also be accepted by the CI,  I totally agree it should be `/jenkins test` as this would help in standardizing the commands for the bot =D. So let me change that in CI so it can be a part of this PR :)

**Comment by ricardozanini** [comment]
Yeah, the `Jenkins test this`sentence also triggers the CI.

**Comment by ricardozanini** [comment]
LOL, we started the test :laughing:

**Comment by Kaitou786** [comment]
Though our whole AWS openshift infra is down and with it our Jenkins server :/ . Will change the phrase when it'll be back

**Comment by Kaitou786** [comment]
@r00ta can you update the comment to `/jenkins test`?

@radtriste @sutaakar FYI,  from now please use this phrase to trigger the pipeline.

**Comment by ricardozanini** [comment]
Can we merge this?

**Comment by Kaitou786** [comment]
> Can we merge this?

I guess we can

**Pull request merged**
