### PR TITLE
[KOGITO-3475] Periodic reconciler error when KogitoInfra is deleted

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-3475

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
related to changes done in https://github.com/kiegroup/kogito-cloud-operator/pull/550

**Review by spolti — APPROVED** [review]

**Review by ricardozanini — COMMENTED** [review]
So if the KogitoInfra gets deleted, what happens with the binds in the services? We're removing the references?

**Comment by vaibhavjainwiz** [comment]
@sutaakar 
This issue occurs because currently we are watching to all create/delete/update event on primary resources inside controller. In this case following thing happened : 

1. you had deleted `kogito_infra`
2. controller-runtime generates delete event for `kogito_infra`
3. KogitoInfra_controller receive delete event for `kogito_infra`
4. KogitoInfra_controller tries to fetch `kogito_infra` object and give error

There could be two ways to tackle this issue :

- Add null handling
- Don't listen for Delete event on primary resource

I am not sure which approach we should follow but we could aviod listening to delete event using code :
```
// Watch for changes to primary resource KogitoInfra
	pred := predicate.Funcs{
		DeleteFunc: func(e event.DeleteEvent) bool {
			return false
		},
	}
	err = c.Watch(&source.Kind{Type: &appv1alpha1.KogitoInfra{}}, &handler.EnqueueRequestForObject{}, pred)
```

**Comment by vaibhavjainwiz** [comment]
> So if the KogitoInfra gets deleted, what happens with the binds in the services? We're removing the references? @vaibhavjainwiz

@ricardozanini 
Currently kogitoServices don't watch for `KogitoInfra` CR. We don't update env var and app prop of kogitoService if referred kogitoInfra removed.

**Comment by sutaakar** [comment]
PR updated to use predicate approach

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by ricardozanini** [comment]
We can use the predicate approach or fetch for the KogitoInfra object and return nil. Listen to the delete event is important to remove/react upon any finalizer we might have. Since we don't have one AFAIR, we can safely add the predicate for now.

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
