### PR TITLE
KOGITO-3058: Improve DEBUG option

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3058
Description: Debug log of test run is not appearing

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
I've tested these changes and now the debug traces from the steps are appearing. But when running in debug mode, the output is not in JSON, I can easily change this but it would imply changes in the operator framework as well and maybe this was done without json on purpose. What do you think @sutaakar ?

**Comment by Sgitario** [comment]
@sutaakar another question, the JIRA says that the command output should be displayed too: "+ set command execution in debug mode as well", but I think it was already working fine (the only problem was that the debug traces were hidden). Am I missing something here?

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
Debug output in plaintext is ok for me.

**Comment by sutaakar** [comment]
About command output - it seems to be implemented already, I think we can consider it as implemented.

**Pull request merged**
