### PR TITLE
KOGITO-3333: Refactor Jobs Service test with keycloak

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3333
Description: Rewriting scenario to check whether the route is forbidden.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
It depends on https://github.com/kiegroup/kogito-apps/pull/457

**Comment by Sgitario** [comment]
I've tested this test using a custom Jobs Service with the changes in https://github.com/kiegroup/kogito-apps/pull/457.

**Comment by ricardozanini** [comment]
Many thanks @Sgitario. This PR will fix the Keycloak errors we are seeing in the PR checks?

**Comment by Sgitario** [comment]
> Many thanks @Sgitario. This PR will fix the Keycloak errors we are seeing in the PR checks?

Nope, those errors will be fixed as part of kiegroup/kogito-apps#457.

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@Sgitario once https://github.com/kiegroup/kogito-apps/pull/457 got merged, could you please set the label `ready`? Then I'll merge it.

**Comment by ricardozanini** [comment]
@Sgitario merge?

**Comment by Sgitario** [comment]
> @Sgitario merge?

Yes

**Pull request merged**
