### PR TITLE
KOGITO-3340: Cucumber Tests: Projects that use Keycloak remains as Te…

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3340
Description: We have some BDD tests that use Keycloak as security provider.
The problem is that when we delete the projects in OCP, the project remains as "Terminating" state.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
I've tested the script when deleting projects with remaining Keycloak and Infinispan resources.
The projects are now gone as expected.

**Review by sutaakar — APPROVED** [review]
Looks good to me.

**Review by MarianMacik — APPROVED** [review]
+1

**Review by ricardozanini — APPROVED** [review]
MANY THANKS!

**Review by spolti — APPROVED** [review]

**Pull request merged**
