### PR TITLE
KOGITO-2477: Deploy files for spring boot

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-2477

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by spolti** [comment]
Tristan is on PTO, can we merge this or do you guys prefer waiting for this approval?

**Comment by Sgitario** [comment]
> Tristan is on PTO, can we merge this or do you guys prefer waiting for this approval?

I think we're good to merge, what do you think @sutaakar ?

**Comment by sutaakar** [comment]
Yes, I think we can merge. @spolti Can you please merge this?

**Comment by sutaakar** [comment]
@Sgitario Please adjust the labels

**Comment by Sgitario** [comment]
> @Sgitario Please adjust the labels

Done

**Pull request merged**
