### PR TITLE
[1.3.x] KOGITO-4444 - Sanitize dashboard name

### PR DESCRIPTION
**Pull request by r00ta**
Cherry pick for https://github.com/kiegroup/kogito-cloud-operator/pull/762

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
@radtriste can we include this one on 1.3.0?

**Comment by ricardozanini** [comment]
@r00ta please update the Release Notes. And here's too: #762

**Comment by radtriste** [comment]
@ricardozanini 1.3.0.Final release did not start and will not for the next couple of days I guess
so we could as it is a bug fix and we will have some nightlies to come

**Comment by ricardozanini** [comment]
@r00ta as soon as you update the RELEASE_NOTES.md we can go.

/jenkins test

**Comment by r00ta** [comment]
> @r00ta as soon as you update the RELEASE_NOTES.md we can go.
> 
> /jenkins test

Hi @ricardozanini , thanks! release notes updated

/jenkins test

**Comment by radtriste** [comment]
I guess we should relaunch the tests once 1.3 nightly images are available (for now there aren't any) and check if it is still failing ...

**Comment by ricardozanini** [comment]
> I guess we should relaunch the tests once 1.3 nightly images are available (for now there aren't any) and check if it is still failing ...

I'm assuming this PR is not ready then?

**Comment by radtriste** [comment]
true ... 
Let's see first the result from https://github.com/kiegroup/kogito-cloud-operator/pull/764

**Comment by radtriste** [comment]
errors here are because of master artifacts taken as default version ... https://github.com/kiegroup/kogito-cloud-operator/pull/764 should solve that

**Comment by radtriste** [comment]
@Kaitou786 Can you check the mirror maven repository ?

**Comment by radtriste** [comment]
We are reverting runtimes/apps/examples on 1.3.x to Quarkus 1.11. Once new artifacts are deployed, I will launch the tests again here.

**Comment by ricardozanini** [comment]
@radtriste still in an error state. The examples are messing with the CI? :cry:

**Comment by radtriste** [comment]
I need to check what is wrong with the source files deployment

**Comment by radtriste** [comment]
bug is weird ... retrying

**Comment by radtriste** [comment]
@r00ta Can you please solve the conflict there ?

**Comment by radtriste** [comment]
all smoke tests passed \o/

**Pull request merged**
