### PR TITLE
[KOGITO-2254] - Integrate Kogito Operator CI PR check with GolangCI-Lint

### PR DESCRIPTION
**Pull request by Kaitou786**
See: https://issues.redhat.com/browse/KOGITO-2254

Signed-off-by: TARUN KHANDELWAL <tarkhand@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
@Kaitou786 this task should be on CircleCI instead. Also, please install golangci-lint locally and try to run it against our code base. Probably you will see lots of warns that need to be addressed in this PR before running the CI on PRs.

**Comment by Kaitou786** [comment]
@ricardozanini I'll shift this to circleCI,  I ran this these see: https://github.com/Kaitou786/kogito-cloud-operator/pull/2/checks?check_run_id=713521366#step:4:60.  Shouldn't we create another JIRA for fixing these issue?

**Comment by ricardozanini** [comment]
@Kaitou786 I don't believe so. They are just minor adjustments for lint, this JIRA should cover it. If you face anything that requires major changes in the code, let me know so we can handle them in a new JIRA.

Tip: integrate the tool with your IDE to avoid pushing to the CI every time to check the errors.

**Comment by Kaitou786** [comment]
@ricardozanini Okay, let me close this PR. I'll open a new one after doing all the changes

**Pull request closed without merging**
