### PR TITLE
[KOGITO-2396] - Integrate `golangci-lint` in `hack/go-lint.sh`

### PR DESCRIPTION
**Pull request by Kaitou786**
Changed the procedure to download the golangci-lint in go-lint.sh

https://github.com/kiegroup/kogito-cloud-operator/pull/388

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Kaitou786** [comment]
The purpose of this PR is to remove the hard coded value of `golangci-lint` version in `go-lint.sh`

**Comment by spolti** [comment]
@Kaitou786 thanks for updating it.
when submitting new pull requests for issues that was already closed, please reopen the jira and attach the new pull request there. It keeps things easier to track.

**Comment by Kaitou786** [comment]
@spolti ah okay, sorry about this. I'll keep this in mind from next time.

**Comment by spolti** [comment]
no worries :)

**Pull request merged**
