### PR TITLE
[KOGITO-2850] Tests: Add Maven mirror configuration for local Maven builds

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-2850

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
Jenkins, test this

**Comment by Kaitou786** [comment]
Jenkins, test this

**Comment by radtriste** [comment]
Jenkins, test this

**Comment by sutaakar** [comment]
The BDD tests will fail until https://github.com/kiegroup/kogito-cloud-operator/pull/444 i smerged.

**Comment by sutaakar** [comment]
Jenkins, test this

**Comment by ricardozanini** [comment]
@sutaakar stills failing. I believe it's related to the examples build? I'm a little worried about this since we supposed to do the cutoff today.

**Comment by radtriste** [comment]
@ricardozanini I have the same worry ... I think we should check with others on Zulip

**Comment by ricardozanini** [comment]
> @ricardozanini I have the same worry ... I think we should check with others on Zulip

OK, will do on more or less 2 and a half hours from now :)

**Comment by radtriste** [comment]
Jenkins, test this

**Comment by radtriste** [comment]
Jenkins, test this

**Comment by radtriste** [comment]
Jenkins, test this

**Comment by ricardozanini** [comment]
jenkins test this

**Comment by sutaakar** [comment]
Jenkins, test this

**Comment by sutaakar** [comment]
Seems like the PR check doesn't rebase the PR source code on top of the target branch, but rather run the PR branch directly.
That would explain previous failures which were fixed in different PR but didn't apply in retriggered checks.

**Comment by Kaitou786** [comment]
> Seems like the PR check doesn't rebase the PR source code on top of the target branch, but rather run the PR branch directly.
> That would explain previous failures which were fixed in different PR but didn't apply in retriggered checks.

It is the intended behaviour, do we want to change it to rebase with latest changes on master?

**Comment by radtriste** [comment]
weird because it is suppose to merge source into target from the Jenkinsfile https://github.com/kiegroup/kogito-cloud-operator/blob/d0669c373631619f81c1ea983c65355827d03a08/Jenkinsfile#L19
See also https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/b70405abc09657ac92161de265874b404dcd9f81/vars/githubscm.groovy#L14

**Comment by Kaitou786** [comment]
Ah, yes just checked, it should be merging the PR with the latest master as it is true in our Jenkinsfile

**Comment by radtriste** [comment]
seems like the PR had an old Jenkinsfile before the latest rebase from @sutaakar => https://jenkins-kogito-tools.apps.kogito.automation.rhmw.io/blue/organizations/jenkins/Kogito%2Fkogito-operator-pr-check/detail/kogito-operator-pr-check/57/pipeline/28

**Pull request merged**
