### PR TITLE
[1.2.x][KOGITO-4245][cherry-pick] - Remove status dependency to get secret credentials (#…

### PR DESCRIPTION
**Pull request by radtriste**
…738)

See: https://issues.redhat.com/browse/KOGITO-4245

cherry-picking to be sure our 1.2.0 operator will work with Infinispan 2.0.7
cherry-pick: https://github.com/kiegroup/kogito-cloud-operator/pull/738

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by Kaitou786 — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Sounds good. Thanks for cherry-picking it! I guess the CI error can be ignored?

**Comment by radtriste** [comment]
Merged as the CI openshift seems to have some problems of terminating namespaces ...
Test will be done on main OCP used for nightlies

**Pull request merged**
