### PR TITLE
[KOGITO-3754] Changed Infinispan channel to 2.0.x

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-3754

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
Another problem came up:
```
TLS handshake failed: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record in Infinispan
```
Checking

**Comment by radtriste** [comment]
https://issues.redhat.com/browse/ISPN-12365
solved in 11.0.5.Final but Operator is using 11.0.4 for now...

**Review by sutaakar — APPROVED** [review]

**Comment by ricardozanini** [comment]
Incorporated in: #646 

Closing.

**Pull request closed without merging**
