### PR TITLE
[KOGITO-2747] Tests: Store log informations about image streams and K…

### PR DESCRIPTION
**Pull request by sutaakar**
…ogito objects

https://issues.redhat.com/browse/KOGITO-2747

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
Can come handy in test failure analysis.
Storing image streams and Kogito objects into log folder.

**Comment by ricardozanini** [comment]
Looks like the OLM has changed their image, I'll take a look. @Kaitou786 same problem we are having in the Nexus Operator.

**Comment by radtriste** [comment]
@ricardozanini shouldn't we put the OLM test only in the nightly ?
like shown here, it there is any external change, then the checks are failing ... and we would need to rebase all PR failing ?

**Comment by ricardozanini** [comment]
> @ricardozanini shouldn't we put the OLM test only in the nightly ?
> like shown here, if there is any external change, then the checks are failing ... and we would need to rebase all PR failing ?

@Kaitou786 is working on running OLM only when `pkg` or CRDs change.

**Comment by ricardozanini** [comment]
@sutaakar can I merge this?

**Comment by sutaakar** [comment]
@ricardozanini yes

**Pull request merged**
