### PR TITLE
[KOGITO-945] CI Feedback loop: Create simple tests

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-945

- Reorganized all tests directly into folder and name them `BDD tests`
- Added `run-smoke-tests` target and `@smoke` tags
- Reorganized quarkus scenario outlines to have `@native` tag
- Added some options to _run-tests_ script to display scenarios before execution and ignore the update of crds
- Change Env to Config as it makes more sense

4 Scenarios are executed in quick tests:
- CLI deploy drools-quarkus-example service (non native)
- CLI deploy jbpm-springboot-example service
- CLI install Kogito Data Index
- CLI install Kogito Jobs Service

That allows to have a quick overview on functionalities.
CLI scenarios were chosen as it tests CLI & Operator together.
What is NOT included: 
- persistence
- native compilation
- complex scenarios

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
Run on QE openshift lasted 5 minutes. Seems a fair runtime.

**Comment by sutaakar** [comment]
@radtriste Just a suggestion, what about renaming 'quick' to 'smoke' and stop calling whole Cucumber tests as 'smoke'?

**Comment by radtriste** [comment]
@sutaakar we can do that indeed. so I remove smoke folder, put everything direct into `test` folder ?
or rename `bdd` ?

**Comment by sutaakar** [comment]
Putting everything to test folder is ok for me. I don't expect any other test type in there.

**Comment by radtriste** [comment]
Rebased
Tested last version:
- smoke => 5 min
- full => 40 min

@spolti if you are good, then we can merge :)

**Comment by sutaakar** [comment]
@radtriste Those are results when 3 concurrent test are running?

**Comment by radtriste** [comment]
yes, sorry should have been more precise

**Comment by spolti** [comment]
Nice work!
can you please rebase?

**Comment by radtriste** [comment]
@spolti Rebase done. We can merge :)

**Comment by spolti** [comment]
awesome, thanks!

**Pull request merged**
