### PR TITLE
[KOGITO-2784] - Bump to 0.13.0

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-2784

Small update to the operator version. Next version we should already have the CI to automate this task.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
> Merging #453 into master will increase coverage by 24.31%.

LOL

@Kaitou786 do you know why?

**Comment by Kaitou786** [comment]
> > Merging #453 into master will increase coverage by 24.31%.
> 
> LOL
> 
> @Kaitou786 do you know why?

Oh the comment will update it hasn't calculated with taking the operator into account.

**Comment by ricardozanini** [comment]
Funny =D

**Comment by ricardozanini** [comment]
For some reason the PR is not being updated with my changes

**Pull request closed without merging**
