### PR TITLE
KOGITO-2738 - Run unit tests only when change in operator or cli file…

### PR DESCRIPTION
**Pull request by Kaitou786**
…s change

see: https://issues.redhat.com/browse/KOGITO-2738

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Kaitou786** [comment]
@ricardozanini do you think it would be okay to shift the OLM test in this new file. So we only run them when there is some change in cli or the operator codebase:
1. lint and bats --> always run for every PR
2. unit test and OLM tests(After unit passes) ---> Run only when change in `pkg/**.go` or `cmd/**.go`

**Comment by ricardozanini** [comment]
> @ricardozanini do you think it would be okay to shift the OLM test in this new file. So we only run them when there is some change in cli or the operator codebase:
> 
>     1. lint and bats --> always run for every PR
> 
>     2. unit test and OLM tests(After unit passes) ---> Run only when change in `pkg/**.go` or `cmd/**.go`

I though that we already talked about this yesterday! hahha

Yes please, also if any thing changes on `deploy` we also need to run OLM integration tests since it's basically a change in the manifests.

I'd say OLM should run on:

- `pkg/***`
- `deploy/**`
- `cmd/**`

**Comment by ricardozanini** [comment]
@radtriste FYI

**Comment by ricardozanini** [comment]
@Kaitou786 do we have control over this Jenkins job? I think it should not run every time as well. cc @radtriste

**Comment by ricardozanini** [comment]
Waiting for checks to finish.

**Comment by Kaitou786** [comment]
> @Kaitou786 do we have control over this Jenkins job? I think it should not run every time as well. cc @radtriste

Yes, we've. We can have it run only when someone comment on the PR like: `Jenkins, run smoke tests`

**Comment by ricardozanini** [comment]
> > @Kaitou786 do we have control over this Jenkins job? I think it should not run every time as well. cc @radtriste
> 
> Yes, we've. We can have it run only when someone comment on the PR like: `Jenkins, run smoke tests`
/
Interesting, I'd say to add this feature. @radtriste @sutaakar wdyt?

**Comment by radtriste** [comment]
any changes in `pkg`, `cmd` or `test` should trigger the smoke tests wdyt ?

**Comment by ricardozanini** [comment]
> any changes in `pkg`, `cmd` or `test` should trigger the smoke tests wdyt ?

Yes, that would be perfect. A workflow to comment automatically here with `jenkins test this` would be cool.

**Comment by radtriste** [comment]
so we would have:
- if `pkg`, `cmd` or `test` is changed, then smoke tests are run automatically
- if not, we could have the `Jenkins run smoke tests`
@Kaitou786 how difficult is it to set ? I cannot configure the hook in Jenkins for the packages ...

**Comment by Kaitou786** [comment]
> so we would have:
> 
>     * if `pkg`, `cmd` or `test` is changed, then smoke tests are run automatically
> 
>     * if not, we could have the `Jenkins run smoke tests`
> 
> 
> @Kaitou786 how difficult is it to set ? I cannot configure the hook in Jenkins for the packages ...

It won't be that much difficult. I can get it ready by tomorrow =D

**Comment by ricardozanini** [comment]
> so we would have:
> 
>     * if `pkg`, `cmd` or `test` is changed, then smoke tests are run automatically
> 
>     * if not, we could have the `Jenkins run smoke tests`
> 
> 
> @Kaitou786 how difficult is it to set ? I cannot configure the hook in Jenkins for the packages ...

@radtriste we would create a special GH workflow to comment here automatically. Don't worry, I think won't need a change in Jenkins

GH and Jenkins working together, how's nice is that? :heart:

**Pull request merged**
