### PR TITLE
KOGITO-2355: BDD tests: Test Jobs service using external Infinispan and Kafka connection

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-2355
Description: Add tests making sure that Jobs service is able to communicate with other components using external Infinispan and Kafka connection.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
Depends on https://github.com/kiegroup/kogito-cloud-operator/pull/489

**Comment by Sgitario** [comment]
I ran the new test and works fine .

**Comment by sutaakar** [comment]
Jenkins, test this

**Comment by radtriste** [comment]
Jenkins, test this

**Pull request merged**
