### PR TITLE
[KOGITO-1670] - Bump to 0.9.1 version

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See:
https://issues.redhat.com/browse/KOGITO-1670

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
Shouldn't this PR rather point to 0.9.x branch, while master being updated to 0.10.0?

**Comment by ricardozanini** [comment]
Not at all. 0.10.0 will also include 0.9.1. I'll cherry pick this one on master as well.

**Comment by radtriste** [comment]
what is point toput a 0.9.1 on master as it will be on 0.9.x ?

**Comment by ricardozanini** [comment]
> what is point to put a 0.9.1 on master as it will be on 0.9.x ?

We will have all the history on master, I think we shouldn't have commits on 0.9.x that are not on master.

**Comment by radtriste** [comment]
1671 on master makes sense but that PR does not to me.
This is specific to 0.9.x release branch.

> We will have all the history on master, I think we shouldn't have commits on 0.9.x that are not on master.

Not fully agree with that. Depending on how far and how many changes we made on master, some fixes will only for 0.9.x branch and not for master.
Versioning is also part of it to me.
master becomes the new 0.10.x (or maybe 1.0.0 if we decide to change) and 0.9.x contains 0.9.0+ versions.

**Comment by ricardozanini** [comment]
> Not fully agree with that. Depending on how far and how many changes we made on master, some fixes will only for 0.9.x branch and not for master.

Indeed.

>  master becomes the new 0.10.x (or maybe 1.0.0 if we decide to change) and 0.9.x contains 0.9.0+ versions.

It will as soon as we merge this and KOGITO-1671

I'll move this PR to 0.9.x branch only, although I do not agree that we should skip this merge into master. @spolti wdyt?

**Comment by ricardozanini** [comment]
Moving it to 0.9.x branch

**Pull request closed without merging**
