### PR TITLE
[KOGITO-1168] - Operator Hub changes

### PR DESCRIPTION
**Pull request by swati-kale**
Removed "Operator" from display name.

Signed-off-by: Swati Kale <swkale@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by swati-kale** [comment]
@ricardozanini @spolti , Please review.

**Comment by ricardozanini** [comment]
@swati-kale thanks for the PR. I don’t have access to the JIRA right now, that’s why I’m going to ask: what’s the motivation behind this change?

Plus the CSV that needs to be changed is the 0.8.0 one. The rc1 will be removed in the next PR merge.

**Comment by swati-kale** [comment]
> @swati-kale thanks for the PR. I don’t have access to the JIRA right now, that’s why I’m going to ask: what’s the motivation behind this change?
> 
> Plus the CSV that needs to be changed is the 0.8.0 one. The rc1 will be removed in the next PR merge.

Ok will do the change at 0.8.0 one.

**Comment by ricardozanini** [comment]
@swati-kale can I also kindly ask you to review other parts of the README.md and the CSV / yaml files that might need this change as well?
Many thanks!

**Pull request merged**
