### PR TITLE
[KOGITO-3420] Adjust PR check tests to execute only operator core fun…

### PR DESCRIPTION
**Pull request by sutaakar**
…ctionality

https://issues.redhat.com/browse/KOGITO-3420

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
Tests being executed:
- Quarkus remote S2I build (specified GitHub URL as a source)
- Quarkus binary build
- SpringBoot build from local source file
- Quarkus build from local source folder
- Quarkus and SpringBoot creation of KogitoRuntime based on existing built image
- Installation of Job service
- Installation of Data index
- Installation of Prometheus

Those are the basic scenarios which came to my mind. I case you think that something else should be added please tell me.

**Comment by sutaakar** [comment]
So far every PR builds example images, using built images from nightly build will be part of another JIRA.

**Comment by ricardozanini** [comment]
Great! Everything run in 23min!!! 

Now I'm happy.

**Review by ricardozanini — APPROVED** [review]

**Comment by Kaitou786** [comment]
Nice!
@sutaakar can you also change the stage name to something `run-smoke-tests` ?

**Comment by sutaakar** [comment]
done
/jenkins test

**Review by Kaitou786 — APPROVED** [review]

**Comment by sutaakar** [comment]
I think it can be merged

**Pull request merged**
