### PR TITLE
KOGITO-3343 - Failover scenario for scaling Infinispan to 0 using BDD…

### PR DESCRIPTION
**Pull request by MarianMacik**
… tests

Many thanks for submitting your Pull Request :heart: :horse_racing: ! 

[KOGITO-3343](https://issues.redhat.com/browse/KOGITO-3343)

PS I have introduced a new tag `@failover` for this kind of scenarios, so I hope it's OK.

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
@MarianMacik I find the title hard to understand. 
Reading the scenario, it is testing that the runtime is reconnecting correctly to Infinispan right ?

**Comment by MarianMacik** [comment]
@radtriste It is testing scaling Infinispan to 0 and back with Kogito Runtime connected to it, so yes. Which part is hard to understand? I can clarify it of course :)

Few possibilities:
* Failover scenario for scaling Infinispan to 0 - omitting using BDD tests
* Failover scenario of Infinispan when scaled to 0

Or I can come up with something else.

**Comment by radtriste** [comment]
Reading `failover scenario [...] for infinispan` I was afraid we check the infinispan down to 0 and then back to 1 ... wanted to be sure of what we are doing here ...
Maybe a more explicit scenario name like `Test Infinispan reconnect with <example-service> using KogitoRuntime` to be clearer on what the scenario is doing ?

**Review by radtriste — APPROVED** [review]

**Comment by MarianMacik** [comment]
Ah you thought that I was actually testing Infinispan and not Kogito-related things? That's not the case, of course.

Currently the scenario is called `Test Infinispan failover with <example-service> using Kogito Runtime`. In my understanding `failover` is more descriptive than `reconnect` as this is mainly about the actual failover capabilities of Kogito, so if the Infinispan becomes unavailable (scaled to 0) and then is available again (scaled to 1), Kogito Runtime is able to continue working. Wdyt?

**Comment by sutaakar** [comment]
@MarianMacik Please add the new tag into the list in readme.

**Comment by sutaakar** [comment]
`Test Kogito Runtime <example-service> failover when connected to/with Infinispan` looks better to me.

**Comment by sutaakar** [comment]
Would it have sense to test also native build?

**Comment by MarianMacik** [comment]
@sutaakar No as the APIs are the same as for JVM build of Quarkus, so I see no point there.

**Review by sutaakar — APPROVED** [review]

**Comment by MarianMacik** [comment]
The new `@failover` tag added to readme and renamed the scenario to be more clear.

**Pull request merged**
