### PR TITLE
[KOGITO-4572] KogitoInfra doesn't detect running Infinispan instance

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-4572

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
I didn't update the readme as the issue is related to https://issues.redhat.com/browse/KOGITO-4477 which is targeting same release, previously it worked well.

**Review by MarianMacik — APPROVED** [review]
Close enough :)

**Comment by ricardozanini** [comment]
Maybe we can also open a follow-up JIRA to update ISPN reference?

**Comment by sutaakar** [comment]
@ricardozanini Created https://issues.redhat.com/browse/KOGITO-4577

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by sutaakar** [comment]
Should we wait for https://github.com/kiegroup/kogito-cloud-operator/pull/781# before merging this PR?

**Comment by ricardozanini** [comment]
No, this is critical. Merging.

**Pull request merged**
