### PR TITLE
[KOGITO-842] - Operator: jbpm-quarkus-example not starting after nati…

### PR DESCRIPTION
**Pull request by spolti**
…ve build due to missing protobuf files

https://issues.redhat.com/browse/KOGITO-842

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
we had a follow-up for that https://issues.redhat.com/browse/KOGITO-959 :)
I will close it when this one is merged.

Let me check first that it works correctly

**Comment by spolti** [comment]
Ok, my bad, didn't see the linked followup on jira.

**Comment by radtriste** [comment]
np

**Comment by spolti** [comment]
@ricardozanini no worries, I always forget to do this =D

**Pull request merged**
