### PR TITLE
[KOGITO-2966] Tests: Remove Strimzi workaround

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-2966

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
I ran the tests using Strimzi several times without reproducing of the issue.

**Comment by sutaakar** [comment]
Waiting for https://github.com/kiegroup/kogito-cloud-operator/pull/489 to be merged first, then tests can be executed.

**Comment by radtriste** [comment]
Jenkins test this

**Comment by sutaakar** [comment]
Jenkins, test this

**Comment by radtriste** [comment]
Jenkins, test this

**Pull request merged**
