### PR TITLE
[KOGITO-3170] Tests: Concurrent map writes error in pod log collector

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

Fixed by using synchronized Map.
https://issues.redhat.com/browse/KOGITO-3170

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by ricardozanini** [comment]
@Kaitou786 do you know if we are having problems with CI?

**Comment by Kaitou786** [comment]
> @Kaitou786 do you know if we are having problems with CI?

Just saw, someone/something removed `ghprb` plugin on Jenkins, maybe by mistake making none of the pipeline to run, installation and configuration in progess

**Comment by sutaakar** [comment]
Test failures are unrelated.
Reported as https://issues.redhat.com/browse/KOGITO-3175 and https://issues.redhat.com/browse/KOGITO-3176

**Pull request merged**
