### PR TITLE
[KOGITO-3568] - Remove spec.httpPort attribute from Operator and HTTP…

### PR DESCRIPTION
**Pull request by Kaitou786**
…_PORT env var from Kogito images

See: https://issues.redhat.com/browse/KOGITO-3568
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Kaitou786** [comment]
For now, we've a problem with our CI due to `githubscm.checkoutIfExists` method is using username/password for authentication, which is deprecated.

**Review by Sgitario — APPROVED** [review]

**Review by Sgitario — CHANGES_REQUESTED** [review]
There is a BDD scenario to cover the functionality that has been removed: update_httpport.feature. Therefore, this feature needs to be removed as well.

**Comment by Kaitou786** [comment]
> update_httpport.feature

Thanks, removed the file :)

**Comment by Kaitou786** [comment]
> There is a BDD scenario to cover the functionality that has been removed: update_httpport.feature. Therefore, this feature needs to be removed as well.

Thanks, removed the file :)

**Review by radtriste — APPROVED** [review]

**Review by Sgitario — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]
I like to see the old code going away. Nice job! You've been doing a great job removing things from the operator. :)

**Comment by ricardozanini** [comment]
@Kaitou786  please update the RELEASE_NOTES.md file. Maybe we should add this rule to the bot?

**Comment by Kaitou786** [comment]
> @Kaitou786 please update the RELEASE_NOTES.md file. Maybe we should add this rule to the bot?

Done, for the bot what kind of rule do we want, every PR which have a milestone should be added to RELEASE_NOTES.md?

**Review by vaibhavjainwiz — CHANGES_REQUESTED** [review]
Remove `HTTPPort` from following locations :
1. https://github.com/Kaitou786/kogito-cloud-operator/blob/f66b32fbf3b72b1a19b81c266024d8417b8a136c/cmd/kogito/command/flag/install_flag.go#L37

2. https://github.com/Kaitou786/kogito-cloud-operator/blob/0576a63b824a4e86fe24733951c3879ce225e6e1/cmd/kogito/command/install/supportingservices_test.go#L63

3. https://github.com/Kaitou786/kogito-cloud-operator/blob/5882b1477d6ab59b833eac700ad0234f1049d976/examples/data-index.yaml#L35

4. https://github.com/Kaitou786/kogito-cloud-operator/blob/5882b1477d6ab59b833eac700ad0234f1049d976/examples/explainability.yaml#L25

5. https://github.com/Kaitou786/kogito-cloud-operator/blob/5882b1477d6ab59b833eac700ad0234f1049d976/examples/trusty.yaml#L36

6. Remove `setHTTPPortInEnvVar` function. No more required.
https://github.com/Kaitou786/kogito-cloud-operator/blob/0576a63b824a4e86fe24733951c3879ce225e6e1/pkg/infrastructure/services/deployment.go#L90

7. No need to pass HTTPPort in function args. We can directly initialize it with `framework.DefaultExposedPort`
https://github.com/Kaitou786/kogito-cloud-operator/blob/154a2d0a1c7af1ab3eabe894d03016268815551f/pkg/infrastructure/services/probe.go#L95

8. Also need to remove `HTTPPort` from kogito-images as well

**Comment by Kaitou786** [comment]
@vaibhavjainwiz I added all your comments can you take a second look :)

**Review by vaibhavjainwiz — APPROVED** [review]
LGTM

**Review by spolti — APPROVED** [review]

**Comment by ricardozanini** [comment]
@sutaakar do you want to take a look before I merge this one?

**Review by sutaakar — APPROVED** [review]
Looks good to me

**Pull request merged**
