### PR TITLE
Cucumber Tests: Add test for explainability-service with Keycloak

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3357

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
This has been tested successfully using a custom image of the explainability service with the required changes part of https://issues.redhat.com/browse/KOGITO-3371

**Comment by Sgitario** [comment]
Depends on https://github.com/kiegroup/kogito-apps/pull/460

**Review by sutaakar — APPROVED** [review]

**Comment by ricardozanini** [comment]
@Sgitario can you please rebase?

**Comment by Sgitario** [comment]
> @Sgitario can you please rebase?

Done.

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Review by r00ta — APPROVED** [review]
Thanks!

**Comment by ricardozanini** [comment]
@Sgitario are we ready?

**Comment by Sgitario** [comment]
> @Sgitario are we ready?

Go for it

**Pull request merged**
