### PR TITLE
[KOGITO-2077] Use buildah instead of podman

### PR DESCRIPTION
**Pull request by radtriste**
Due to problems with podman in the Jenkins slave container ...

https://issues.redhat.com/browse/KOGITO-2077

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Kaitou786** [comment]
@radtriste can we change the agent label as part of this PR? I changed the label from `golang` to `operator-slave` on the Jenkins configuration?

**Comment by spolti** [comment]
@msmagnanijr shouldn't the jenkins job be triggered here?

**Comment by msmagnanijr** [comment]
> @msmagnanijr shouldn't the jenkins job be triggered here?

yes... @radtriste could you please add the trigger to this PR? the same as we did here  https://github.com/kiegroup/kogito-images/blob/master/Jenkinsfile-Nightly#L7

**Comment by Kaitou786** [comment]
@msmagnanijr shouldn't the per PR check configuration is done while creating the multibranch pipeline on jenkins?

**Comment by radtriste** [comment]
added

**Comment by radtriste** [comment]
@Kaitou786 PR check will be added once this PR is merged or ?
Else it will fail IMHO, because as we changed the Jenkinsfile here, the sandbox will backup to Jenkinsfile from master, for security reasons

**Comment by Kaitou786** [comment]
I think the Jenkins pick up Jenkinsfile from the PR and not from the master branch, so it may fail on other pending PR right now as they have the old Jenkinsfile, but it will succeed on this one and we'll get to see if everything is fine

**Comment by radtriste** [comment]
Not if you changed the Jenkinsfile in the PR.
For security reasons, if such a change happens, then Jenkins is retrieving the file from master to be executed and not from the PR.

**Comment by Kaitou786** [comment]
You can change that in the configuration side of Jenkins to discover Jenkinsfile from the PR if they are `contributors` of the repository, by default it is set to `From users with admin or write permission` . That's what we've done for kogito-image repo.

**Comment by msmagnanijr** [comment]
> I think the Jenkins pick up Jenkinsfile from the PR and not from the master branch, so it may fail on other pending PR right now as they have the old Jenkinsfile, but it will succeed on this one and we'll get to see if everything is fine

yep, this is the expected behavior.

**Pull request merged**
