### PR TITLE
[KOGITO-4521] - Add `kogito-variables-events` as hard coded topic lis…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…t in operator which need to be created while installing data-index service

https://issues.redhat.com/browse/KOGITO-4521

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
Lgtm. Please also cherry pick to 1.3.x

**Review by MarianMacik — APPROVED** [review]

**Comment by vaibhavjainwiz** [comment]
Raised cherry pick request for 1.3.x
https://github.com/kiegroup/kogito-cloud-operator/pull/770

**Review by ricardozanini — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by ricardozanini** [comment]
@vaibhavjainwiz I can merge this one, but are you comfortable rebasing with #740?

**Comment by spolti** [comment]
probably will be better to wait on #740 and there is a conflict here as well :)

**Comment by vaibhavjainwiz** [comment]
> probably will be better to wait on #740 and there is a conflict here as well :)

I had resolved all merge conflicts

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@radtriste can this failing check be ignored?

**Comment by radtriste** [comment]
codecov error is not related to this PR so I guess we can

**Comment by spolti** [comment]
ok, merging and resolving the jira.

**Pull request merged**
