### PR TITLE
[KOGITO-2100][KOGITO-2706] - Add Operator Framework OLM Integration T…

### PR DESCRIPTION
**Pull request by Kaitou786**
…ests to Kogito Operator CI and Change kogito-infra name in the CR

https://issues.redhat.com/browse/KOGITO-2706
https://issues.redhat.com/browse/KOGITO-2100

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
We are sending one PRs to solve two issues because they are related and depends on each other. KOGITO-2706 is a blocker that can jeopardize our PRs to OperatorHub.

**Comment by ricardozanini** [comment]
When we afford a node for ourselves to use in these workflows, I believe we will drop the OLM Integration Test to 3~5min. But it's pretty cool to see this test running <3

**Comment by Kaitou786** [comment]
> When we afford a node for ourselves to use in these workflows, I believe we will drop the OLM Integration Test to 3~5min. But it's pretty cool to see this test running <3

Yes, Indeed when I run them locally they take around 5-6 minutes to complete

**Comment by ricardozanini** [comment]
Waiting for @sutaakar blessing :D

**Pull request merged**
