### PR TITLE
[KOGITO-703] Installs Kogito Operator if available in the OperatorHub

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.redhat.com/browse/KOGITO-703

Instead of given the annoying WARN that the Operator is available in the hub, installs it via Hb Subscription.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
@radtriste I haven't tested in an actual cluster yet. But if you have the time (and are brave enought) to check this one tomorrow, I ll give you a lollipop. :lollipop: 

I'll test this one tomorrow, third PR in a row, I'm exhausted.

Merry Xmas! :christmas_tree:

**Comment by ricardozanini** [comment]
@msmagnanijr this one might interest you.

**Comment by radtriste** [comment]
Working after some changes into the code.

**meta.go**
```
import (
	[...]
  	olmapiv1 "github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1"
	olmapiv1alpha1 "github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1"
)
[...]
var(
	// KindOperatorGroup ...
	KindOperatorGroup = DefinitionKind{"OperatorGroup", false, olmapiv1.SchemeGroupVersion}
	// KindSubscription ...
	KindSubscription = DefinitionKind{"Subscription", false, olmapiv1alpha1.SchemeGroupVersion}
)
[...]
func GetRegisteredSchema() *runtime.Scheme {
[...]
	metav1.AddToGroupVersion(s, olmapiv1.SchemeGroupVersion)
	metav1.AddToGroupVersion(s, olmapiv1alpha1.SchemeGroupVersion)
[...]
```

**client.go**
```
[...]
func newControllerCliOptions() controllercli.Options {
[...]
	mapper.Add(olmapiv1.SchemeGroupVersion.WithKind(meta.KindOperatorGroup.Name), &restScope{name: apimeta.RESTScopeNameNamespace})
	mapper.Add(olmapiv1alpha1.SchemeGroupVersion.WithKind(meta.KindSubscription.Name), &restScope{name: apimeta.RESTScopeNameNamespace})
[...]
```

**Comment by radtriste** [comment]
One other thing I was thinking about: Could we have the option to change channel and/or operatorsource as option into the command line ?
Would be useful for dev ;)

**Comment by ricardozanini** [comment]
> One other thing I was thinking about: Could we have the option to change channel and/or operatorsource as option into the command line ?
> Would be useful for dev ;)

Maybe on a new JIRA perhaps?

**Comment by radtriste** [comment]
> > One other thing I was thinking about: Could we have the option to change channel and/or operatorsource as option into the command line ?
> > Would be useful for dev ;)
> 
> Maybe on a new JIRA perhaps?

Created https://issues.redhat.com/browse/KOGITO-833

**Pull request merged**
