### PR TITLE
[KOGITO-3939] Adjust readiness and liveness probes

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta ksuta@redhat.com

https://issues.redhat.com/browse/KOGITO-3939

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
Will be ready once https://github.com/kiegroup/kogito-cloud-operator/pull/676 get merged.

**Review by ricardozanini — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by sutaakar** [comment]
Test failure caused by race condition, reported as https://issues.redhat.com/browse/KOGITO-3953
/jenkins test

**Comment by sutaakar** [comment]
`The CustomResourceDefinition "kogitoruntimes.app.kiegroup.org" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions`
The CRDs are messed again in the instance. @Kaitou786 Can you please remove the old CRDs?

**Comment by sutaakar** [comment]
@ricardozanini Could you please merge this?

**Pull request merged**
