### PR TITLE
[KOGITO-3278] Tests: Enable Kogito infra for Kafka only when URL and …

### PR DESCRIPTION
**Pull request by sutaakar**
…Instance are empty

https://issues.redhat.com/browse/KOGITO-3278

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by sutaakar** [comment]
CI issue on BDD tests

**Comment by sutaakar** [comment]
@ricardozanini I guess it can be merged. I have checked it locally and works as expected. The CI doesn't seem to work any time soon.

**Pull request merged**
