### PR TITLE
[KOGITO-3960] Store OLM logs for PR checks and nightly builds

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-3960

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by sutaakar** [comment]
`No space left on device`
Lets try it again
/jenkins test

**Review by Kaitou786 — APPROVED** [review]

**Comment by sutaakar** [comment]
Seems better now, but the failure seems to be related to environment:
` 2020-12-03 16:10:51  | 2020-12-03 16:10:51  |        | dmn-drools-quarkus-metrics-86578cdcb4-vnjk5.164d40c3c1448f98  | -     | -                                            | Warning  | Evicted              | -        | -                  | -                                 | The node had condition: [DiskPressure].                                                                                                                                                                                `

**Pull request merged**
