### PR TITLE
Update version to 1.3.0-snapshot

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
I think there is a problem on the operator. checking the test failures

**Review by spolti — APPROVED** [review]
approving but let's wait the CI to see what is happening.

**Review by sutaakar — APPROVED** [review]

**Comment by ricardozanini** [comment]
These test errors are related to our examples?

**Comment by radtriste** [comment]
yep... looks like there is an artifacts refresh problem

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
artifacts problem is our mirror repository ... testing on RHBA Jenkins and build is passing: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/dsl/job/nightly/job/1.3.x/job/kogito-operator-deploy/5/

**Comment by radtriste** [comment]
seems there are still some Maven mirror refresh problems ...
Tested on another OCP and problems are not the same way. latest was the `dmn-drools-quarkus-metrics` cannot be built.
This is not introduced by this PR but by updates on pom/bom for Quarkus 1.12 and property version alignment done the last days ...
Will merge this PR to that the nightly run can happen correctly with 1.3 images

**Pull request merged**
