### PR TITLE
[0.17.x][KOGITO-2562] SW: Auto-creation of Knative Eventing resource

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Many thanks for submiting your Pull Request :heart:! 

Cherry-pick for https://issues.redhat.com/browse/KOGITO-2562
PR => https://github.com/kiegroup/kogito-cloud-operator/pull/602

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Comment by ricardozanini** [comment]
@radtriste your call. You can merge this anytime now.

**Comment by radtriste** [comment]
@ricardozanini we would need to cherry-pick https://github.com/kiegroup/kogito-examples/pull/401 as well or ?

**Comment by ricardozanini** [comment]
Yes! I will do it as soon as I set down in the computer :)

**Comment by ricardozanini** [comment]
@radtriste done:
https://github.com/kiegroup/kogito-examples/pull/414

**Pull request merged**
