### PR TITLE
[KOGITO-600] - Removing default build limits

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.jboss.org/browse/KOGITO-600

Simple update to the KogitoApp to remove default builds, avoiding side effects like the one exemplified in the JIRA

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
> That means that the workaround on https://issues.jboss.org/browse/KOGITO-504 don't apply anymore or ?

Exactly. But this can be consider a workaround anyway, since will use all resources that are available in the node.

**Comment by ricardozanini** [comment]
> there is only this tests which does limits tests?

I didn't get it. What did you mean? 

In the scenario that we tackled, a cluster admin set the Limit below 1 CPU and 2Gi of memory for builds.

That's fine since the user can workaround this by setting a limit below this values in the Kogito App CR.

The problem is that once we set a value for resources limits in BC, the init containers for s2i builds, also set their own limits and we **don't have control over it**. We don't have an option "blank limits" in our CR since we set default limit builds, that's the problem. 

Removing the defaults and leaving this values to the cluster admin/dev to set would be better and more "wider" approach, since setting default limits bring other consequences like the exemplified above.

**Comment by spolti** [comment]
I meant, in the operator tests, all tests that  is related with build limits are the one you removed?

**Comment by ricardozanini** [comment]
> I meant, in the operator tests, all tests that is related with build limits are the one you removed?

I just removed the ones that consider setting the default.

**Comment by ricardozanini** [comment]
@xiezhang7 could you please take a look?

**Pull request merged**
