### PR TITLE
[KOGITO-998] Setup all run-smoke params into Makefile

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-998

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by radtriste** [comment]
will add also some bats tests

**Comment by radtriste** [comment]
added some bats tests. Please let me know @ricardozanini @sutaakar

**Comment by sutaakar** [comment]
Looks good to me.

**Comment by ricardozanini** [comment]
@radtriste are we ready?

**Comment by radtriste** [comment]
@ricardozanini we are :)

**Pull request merged**
