### PR TITLE
[KOGITO-282] Remove "name" field from "spec" of the CR

### PR DESCRIPTION
**Pull request by xiezhang7**
Jira: https://issues.jboss.org/browse/KOGITO-282

Description: remove "name" field from "spec" of the CRs.

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @ricardozanini @bmozaffa @tchughesiv , could you please review this pull request? Thanks.

**Comment by ricardozanini** [comment]
@xiezhang7 many thanks for this PR! I'm going to merge it after the release cut of the 0.4.0.

**Comment by xiezhang7** [comment]
> @xiezhang7 I took a second look at the PR and found that we are missing updates:
> 
> 1. [README.md file](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#install-data-index-with-operator-catalog-olm)
> 2. [Examples CR](https://github.com/kiegroup/kogito-cloud-operator/blob/master/deploy/examples/springboot.yaml#L6)
> 
> Could you kindly update them?
> 
> Many thanks!

Updated. Thanks, @ricardozanini .

**Comment by ricardozanini** [comment]
Looks like that 0.4.0 will be delayed, so minor PRs like this one will get merged.

**Pull request merged**
