### PR TITLE
[KOGITO-3378] - Upgrade from v1alpha1 to v1beta1 CRD version

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Many thanks for submitting your Pull Request :heart:! 

Jira issue : https://issues.redhat.com/browse/KOGITO-3378

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by vaibhavjainwiz** [comment]
depends on https://github.com/kiegroup/kogito-cloud-operator/pull/648

**Comment by radtriste** [comment]
> depends on #648

you mention this PR here :)

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@vaibhavjainwiz can you check the OLM failure ?

**Comment by vaibhavjainwiz** [comment]
> @vaibhavjainwiz can you check the OLM failure ?

It fails because it checkout and run `process-quarkus-example` from kogito-example repo which still contains old crd version. I had also raised PR to update kogito-examples as well.

**Comment by ricardozanini** [comment]
@vaibhavjainwiz can you please rebase?

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@sutaakar is this CI error related to Kafka?

**Comment by sutaakar** [comment]
There are errors in log:
`The CustomResourceDefinition "kogitobuilds.app.kiegroup.org" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions`
Maybe old CRD needs to be removed first? Or should we define both versions in CRD?

**Comment by ricardozanini** [comment]
> There are errors in log:
> `The CustomResourceDefinition "kogitobuilds.app.kiegroup.org" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions`
> Maybe old CRD needs to be removed first? Or should we define both versions in CRD?

Ideally the old should be removed. The BDD tests aren't removing the CRDs in every run?

**Comment by Kaitou786** [comment]
I deleted the old CRDs from the cluster and rerun the tests. Now they are passing :)

**Comment by sutaakar** [comment]
>      Ideally the old should be removed. The BDD tests aren't removing the CRDs in every run?

BDD tests are updating CRD in every run. It seems that in such case update is not possible.

**Comment by ricardozanini** [comment]
> > ```
> >  Ideally the old should be removed. The BDD tests aren't removing the CRDs in every run?
> > ```
> 
> BDD tests are updating CRD in every run. It seems that in such case update is not possible.

It's not because it's another CRD, so my suggestion is to delete the CRD and re-create it instead. I believe this is the approach taken on OLM.

**Comment by ricardozanini** [comment]
@spolti wanna take a look?
@vaibhavjainwiz could you please cherry-pick this one to 1.x branch? Many thanks!

**Comment by ricardozanini** [comment]
In the future, when we release `v1`, [we will probably have multiple versions set](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/).

**Comment by vaibhavjainwiz** [comment]
> @spolti wanna take a look?
> @vaibhavjainwiz could you please cherry-pick this one to 1.x branch? Many thanks!

@ricardozanini I will cherry-pick these changes to 1.x branch once this PR merged

**Comment by ricardozanini** [comment]
> > @spolti wanna take a look?
> > @vaibhavjainwiz could you please cherry-pick this one to 1.x branch? Many thanks!
> 
> @ricardozanini I will cherry-pick these changes to 1.x branch once this PR merged

Don't mind waiting for it to be merged. I just merged anyway. Thanks!

**Review by spolti — APPROVED** [review]

**Comment by vaibhavjainwiz** [comment]
> > > @spolti wanna take a look?
> > > @vaibhavjainwiz could you please cherry-pick this one to 1.x branch? Many thanks!
> > 
> > 
> > @ricardozanini I will cherry-pick these changes to 1.x branch once this PR merged
> 
> Don't mind waiting for it to be merged. I just merged anyway. Thanks!

@ricardozanini I had raised cherry-pick PR for KOGITO-3378
https://github.com/kiegroup/kogito-cloud-operator/pull/651

**Pull request merged**
