### PR TITLE
[KOGITO-2702] Optimize bats tests runtime

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-2702

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by ricardozanini** [comment]
NOW WE ARE TALKING!

I asked @Kaitou786 yesterday about this, I was wondering why our bats tests were taking that long to run. Many thanks for this!

**Comment by ricardozanini** [comment]
Can we merge this now?

**Comment by radtriste** [comment]
Yeah .. before for each call, it was running the `go test` command, so it needed to compile for each test... That is what took so long ...



> Can we merge this now?

I just noticed a change I could add in this PR. There is no rush or ?

**Comment by radtriste** [comment]
nevermind the change is not possible ... Waiting for @sutaakar approval and then we can merge

**Pull request merged**
