### PR TITLE
KOGITO-3281: Cucumber Tests: Add test for trusty-service with Keycloak

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/KOGITO-3281
Description: Add test for trusty-service with Keycloak

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by Sgitario** [comment]
Depends on https://issues.redhat.com/browse/KOGITO-3312

**Review by r00ta — APPROVED** [review]
Thanks!

**Comment by Sgitario** [comment]
Hi @sutaakar, can you have a look into this PR when you got a minute? Thanks in advance!

**Review by sutaakar — APPROVED** [review]
Looks good to me

**Comment by ricardozanini** [comment]
Is it ready?

**Comment by Sgitario** [comment]
> Is it ready?

Ready

**Pull request merged**
