### PR TITLE
[KOGITO-3947] - Fix infinite reconciliation loop when no env var is defined

### PR DESCRIPTION
**Pull request by ricardozanini**
See: https://issues.redhat.com/browse/KOGITO-3947

@sutaakar I believe this will fix this problem. Can you please take a look? :)

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
`Too Many Requests` while pulling quay.io/kiegroup/kogito-quarkus-ubi8-s2i-nightly:latest
/jenkins test

**Review by sutaakar — APPROVED** [review]
Looks good to me, works as expected.

**Review by spolti — APPROVED** [review]

**Comment by ricardozanini** [comment]
OLM check is under review, merging since it's a critical bug.

**Pull request merged**
