### PR TITLE
Mocking approach for testing

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Many thanks for submiting your Pull Request :heart:! 

As discussed in last meeting, I am sharing mocking approach with testity framework.
We are already using `testify` framework in our project to write assert in unit test cases. I had implement mocking services of `testify` framework to write test cases with mocking of another service.

With this approach we can cover every scenerio in our project. 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by sutaakar** [comment]
I can see a meaning for mocking in case we want to simulate some specific conditions/issues like failure in Kubernetes API call, something what is hard to simulate with current functionality. Not much for "common" usage.

Mocking would allow us to run unit tests for "high level" structures, by isolating it from lower levels. But do we want it?
IMHO such approach would bind the tests with the implementation, in case of refactoring we would have to basically rewrite the tests. 
We would still have to keep some functional tests to make sure that application layers can work together, making sure that upper layer is able to process response from lower layer.

Unit tests have sense in case of simple functions without much dependencies and integrations. But for complex functionality it is from my point of view important to make sure it follows contract and correctly integrates with all components.

**Comment by ricardozanini** [comment]
Agree with @sutaakar, IMO I don't see why mocking these internals on command side. The main problem that we'd like to test is actually to see if the flags are been converted into the correct CR structure. Mocking this behavior would not test what we really need.

**Comment by ricardozanini** [comment]
@vaibhavjainwiz can we close this one?

**Comment by vaibhavjainwiz** [comment]
> @vaibhavjainwiz can we close this one?

Please close it

**Pull request closed without merging**
