### PR TITLE
[KOGITO-422] Upgrade to Operator SDK 0.11.0

### PR DESCRIPTION
**Pull request by xiezhang7**
Jira: https://issues.jboss.org/browse/KOGITO-422
Description: upgrade the operator to use operator-sdk 0.11.0
References: [v0.11.x upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v011x)

Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.MD#sending-a-pull-request)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

### CODE REVIEW

**Comment by xiezhang7** [comment]
> Have you run the e2e test on a OCP 3.11 cluster?

@ricardozanini I tried the e2e test. 
I have to remove the [subresource annotation](https://github.com/kiegroup/kogito-cloud-operator/pull/85/files#diff-d3d14d5602bd9593c4a4a61e898a922e) for `KogitoDataIndex` on OCP 3.11. 
Otherwise, I get error when deploying the `KogitoDataIndex` CRD: `must only have \"properties\", \"required\" or \"description\" at the root if the status subresource is enabled`.
Although, I am not sure if [Status Subresource](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource) is mandatory for `KogitoDataIndex`. `KogitoApp` doesn't use this annotation. 
OCP 4.x doesn't have any problem with this.

**Comment by ricardozanini** [comment]
@xiezhang7 it's not mandatory, but it's a good feature to have. Once 3.11 got deprecated, we can have this back.

Could you please just rebase your commit to get the last README update? Many thanks!

**Comment by xiezhang7** [comment]
> Could you please just rebase your commit to get the last README update? Many thanks!

@ricardozanini I have rebased the commits. Thanks.

**Comment by xiezhang7** [comment]
> @xiezhang7 I guess we need to change the pre req as well:
> https://github.com/kiegroup/kogito-cloud-operator/pull/85/files#diff-04c6e90faac2675aa89e2176d2eec7d8L53

Thanks, @ricardozanini . It is corrected.

**Pull request merged**
